apiVersion: v1
kind: Namespace
metadata:
  name: nids-system
  labels:
    name: nids-system
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nids-config
  namespace: nids-system
data:
  production.yaml: |
    model:
      architecture:
        input_dim: 79
        hidden_dims: [64, 32, 16, 8]
        activation: relu
        dropout_rate: 0.1
      training:
        learning_rate: 0.001
        batch_size: 32
        epochs: 100
        early_stopping_patience: 10
        validation_split: 0.2
      threshold:
        method: "percentile"
        value: 95.0
        auto_tune: true
    
    data:
      preprocessing:
        scaler: "standard"
        handle_missing: "drop"
      paths:
        raw_data: "/app/data/raw"
        processed_data: "/app/data/processed"
        models: "/app/models"
    
    api:
      host: "0.0.0.0"
      port: 8000
      workers: 4
      timeout: 30
      cors:
        allow_origins: ["*"]
        allow_methods: ["GET", "POST"]
        allow_headers: ["*"]
    
    logging:
      level: "INFO"
      format: "json"
      file_rotation: true
      max_bytes: 10485760
      backup_count: 5
---
apiVersion: v1
kind: Secret
metadata:
  name: nids-secrets
  namespace: nids-system
type: Opaque
data:
  api-key: bmlkcy1hcGkta2V5LTEyMw==  # base64 encoded "nids-api-key-123"
  db-password: cGFzc3dvcmQxMjM=       # base64 encoded "password123"
