# Testing Environment Configuration
# This configuration is optimized for automated testing

# Model Configuration
model:
  architecture:
    input_dim: 10  # Smaller for faster tests
    hidden_dims: [16, 8, 16]  # Simple architecture
    activation: "relu"
    dropout_rate: 0.1
    batch_norm: false  # Simpler for tests
    layer_norm: false

# Training Configuration  
training:
  epochs: 5  # Very fast training for tests
  batch_size: 16  # Small batches
  learning_rate: 0.01  # Higher for faster convergence
  weight_decay: 0
  optimizer: "adam"
  scheduler: "none"
  
  early_stopping_enabled: false  # Disabled for predictable tests
  early_stopping_patience: 5
  early_stopping_min_delta: 1e-3
  
  validation_split: 0.2
  shuffle: true
  seed: 42  # Fixed seed for reproducibility
  deterministic: true
  
  device: "cpu"  # Force CPU for consistent tests
  mixed_precision: false
  
  checkpoint_enabled: false  # No checkpoints in tests
  checkpoint_freq: 1
  save_best_only: false

# Data Configuration
data:
  source_path: "tests/fixtures/test_data.csv"
  source_format: "csv"
  encoding: "utf-8"
  
  feature_columns:
    - "feature1"
    - "feature2"
    - "feature3"
    - "feature4"
  
  target_column: "class"
  normal_class: "normal"
  anomaly_classes: ["attack"]
  
  scaling_method: "minmax"
  feature_range: [0, 1]
  handle_missing: "drop"
  missing_threshold: 0.1
  outlier_detection: "none"  # Disabled for tests
  outlier_threshold: 3.0
  
  train_ratio: 0.6
  val_ratio: 0.2
  test_ratio: 0.2
  stratify: false  # Simpler for tests
  
  cache_enabled: false  # No caching in tests
  cache_dir: "tests/cache"

# Threshold Configuration
thresholds:
  methods: ["percentile"]  # Single method for simplicity
  percentile_value: 90.0
  statistical_factor: 2.0
  statistical_method: "std"
  roc_metric: "f1"
  target_precision: 0.9
  target_recall: 0.8
  default_method: "percentile"

# API Configuration
api:
  title: "NIDS Autoencoder API (Testing)"
  description: "Network Intrusion Detection System - Test Environment"
  version: "1.0.0-test"
  host: "127.0.0.1"
  port: 8001  # Different port to avoid conflicts
  workers: 1
  
  max_batch_size: 50  # Small for tests
  timeout_seconds: 10  # Short timeout
  keepalive_timeout: 5
  
  authentication_enabled: false
  api_key_header: "X-API-Key"
  allowed_origins: ["*"]
  
  rate_limit_enabled: false
  requests_per_minute: 1000
  burst_size: 100
  
  metrics_enabled: false  # Disabled for cleaner tests
  health_check_enabled: true
  request_logging: false
  
  docs_enabled: false
  docs_url: "/docs"
  redoc_url: "/redoc"

# Database Configuration
database:
  enabled: false  # No database in tests
  host: "localhost"
  port: 5432
  database: "nids_test"
  username: "test_user"
  password: ""
  
  pool_size: 1
  max_overflow: 1
  pool_timeout: 5
  pool_recycle: 300
  
  echo: false
  echo_pool: false

# Cache Configuration
cache:
  enabled: false  # No caching in tests
  
  redis_enabled: false
  redis_host: "localhost"
  redis_port: 6379
  redis_db: 15  # Test database
  redis_password: ""
  
  memory_enabled: false
  max_size: 100
  ttl_seconds: 60
  
  file_enabled: false
  cache_dir: "tests/cache"

# Logging Configuration
logging:
  level: "WARNING"  # Minimal logging in tests
  format: "%(levelname)s - %(message)s"  # Simple format
  date_format: "%H:%M:%S"
  
  console_enabled: false  # No console output in tests
  file_enabled: false  # No file logging in tests
  json_enabled: false
  syslog_enabled: false
  
  log_dir: "tests/logs"
  log_file: "test.log"
  max_file_size: 1048576  # 1MB
  backup_count: 1
  
  json_file: "test.json"
  
  uvicorn_level: "ERROR"
  sqlalchemy_level: "ERROR"
  
  async_logging: false

# Monitoring Configuration
monitoring:
  enabled: false  # Disabled in tests
  
  prometheus_enabled: false
  prometheus_port: 9091
  namespace: "nids_test"
  
  health_check_interval: 300  # Infrequent
  health_check_timeout: 1
  
  alerting_enabled: false
  alert_webhook_url: ""
  
  profiling_enabled: false
  memory_profiling: false

# Security Configuration
security:
  cors_enabled: true
  cors_origins: ["*"]  # Permissive for tests
  cors_methods: ["GET", "POST", "PUT", "DELETE"]
  
  jwt_secret: "test-secret-key"  # Fixed for tests
  jwt_algorithm: "HS256"
  jwt_expiration: 3600
  
  encryption_key: "test-encryption-key"  # Fixed for tests
  
  max_request_size: 1048576  # 1MB
  validate_content_type: false  # Relaxed for tests
  
  security_headers_enabled: false

# Deployment Configuration
deployment:
  environment: "testing"
  debug: true
  
  model_path: "tests/fixtures/test_model.pth"
  scaler_path: "tests/fixtures/test_scaler.pkl"
  config_path: "tests/fixtures/test_config.yaml"
  
  container_name: "nids-autoencoder-test"
  image_tag: "test"
  
  namespace: "nids-test"
  replicas: 1
  
  cpu_limit: "200m"
  memory_limit: "256Mi"
  cpu_request: "100m"
  memory_request: "128Mi"

# Metadata
config_version: "1.0.0"
created_at: "2025-07-29T00:00:00"
updated_at: "2025-07-29T00:00:00"
